//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iş_takip_proje.entity1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbladmin
    {
        public int ID { get; set; }
        public string kulalnıcı { get; set; }
        public string sifre { get; set; }
    }
}
