//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iş_takip_proje.entity1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfirmalar
    {
        public int ID { get; set; }
        public string yetkili { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public string sektör { get; set; }
        public string il { get; set; }
        public string ilçe { get; set; }
        public string adres { get; set; }
        public string ad { get; set; }
    }
}
