//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iş_takip_proje.entity1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGörevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGörevler()
        {
            this.tblgörevdetaylar = new HashSet<tblgörevdetaylar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> görevVeren { get; set; }
        public Nullable<int> görevAlan { get; set; }
        public string açıklama { get; set; }
        public string durum { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblgörevdetaylar> tblgörevdetaylar { get; set; }
        public virtual tblpersonel tblpersonel { get; set; }
        public virtual tblpersonel tblpersonel1 { get; set; }
    }
}
