//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iş_takip_proje.entity1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpersonel()
        {
            this.tblGörevler = new HashSet<tblGörevler>();
            this.tblGörevler1 = new HashSet<tblGörevler>();
        }
    
        public int ID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string mail { get; set; }
        public string telefon { get; set; }
        public string görsel { get; set; }
        public Nullable<int> departman { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGörevler> tblGörevler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGörevler> tblGörevler1 { get; set; }
        public virtual tbldepartmanlar tbldepartmanlar { get; set; }
    }
}
